In [1]:
import pandas as pd

In [2]:
# Association Rule Mining
# Using the full cleaned dataset and extracting just the survey response ID (representing the customer) and the titles of products purchased by each customer

# Using a copy of the dataset before encoding, so we can see item names when doing ARM instead of numeric labels
data_unencoded = pd.read_csv('/workspaces/group-project-bas-team/data/data_unencoded.csv')


# Attempting ARM with categories first
purchases_by_customer = data_unencoded.groupby('Survey ResponseID')['Category'].apply(list).tolist()

In [ ]:
%pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.16.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from mlxtend) (2.4.3)
Requirement already satisfied: pandas>=2.3.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from mlxtend) (3.0.1)
Requirement already satisfied: scikit-learn>=1.8.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from mlxtend) (1.8.0)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Requirement already satisfied: joblib>=1.5.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from mlxtend) (1.5.3)
Collecting contourpy>=1.0.1 (from matplotlib>=3.10.8->mlxtend)
  Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib>=3.10.8->mlxtend)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.10.8->mlxtend)
  Downloading fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (117 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.10.8->mlxtend)
  Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Collecting pillow>=8 (from matplotlib>=3.10.8->mlxtend)
  Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib>=3.10.8->mlxtend)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 28.1 MB/s  0:00:00
Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 43.4 MB/s  0:00:00
Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 36.2 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 35.7 MB/s  0:00:00
Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 47.7 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, mlxtend
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [mlxtend]m7/8 [mlxtend]ib]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.8 mlxtend-0.24.0 pillow-12.1.1 pyparsing-3.3.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from mlxtend.preprocessing import TransactionEncoder

encoder = TransactionEncoder()
encoding = encoder.fit_transform(purchases_by_customer)
transaction_data = pd.DataFrame(encoding, columns=encoder.columns_)

In [ ]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(transaction_data, min_support=0.5, use_colnames=True)
frequent_itemsets

     support                                           itemsets
0   0.831510                             frozenset({ABIS_BOOK})
1   0.531729                               frozenset({BATTERY})
2   0.514223                                frozenset({BEAUTY})
3   0.687090                   frozenset({CELLULAR_PHONE_CASE})
4   0.590810                      frozenset({CHARGING_ADAPTER})
5   0.704595                      frozenset({ELECTRONIC_CABLE})
6   0.698031                            frozenset({HEADPHONES})
7   0.676149                  frozenset({HEALTH_PERSONAL_CARE})
8   0.518600                                  frozenset({HOME})
9   0.514223                            frozenset({MEDICATION})
10  0.564551                frozenset({NUTRITIONAL_SUPPLEMENT})
11  0.566740                                 frozenset({PANTS})
12  0.520788      frozenset({PORTABLE_ELECTRONIC_DEVICE_COVER})
13  0.529540                      frozenset({SCREEN_PROTECTOR})
14  0.711160                                 frozenset({SHIRT})
15  0.573304                                 frozenset({SHOES})
16  0.538293                      frozenset({SKIN_MOISTURIZER})
17  0.527352                                 frozenset({SOCKS})
18  0.617068        frozenset({CELLULAR_PHONE_CASE, ABIS_BOOK})
19  0.512035           frozenset({CHARGING_ADAPTER, ABIS_BOOK})
20  0.614880           frozenset({ELECTRONIC_CABLE, ABIS_BOOK})
21  0.603939                 frozenset({ABIS_BOOK, HEADPHONES})
22  0.592998       frozenset({HEALTH_PERSONAL_CARE, ABIS_BOOK})
23  0.509847     frozenset({NUTRITIONAL_SUPPLEMENT, ABIS_BOOK})
24  0.520788                      frozenset({PANTS, ABIS_BOOK})
25  0.641138                      frozenset({SHIRT, ABIS_BOOK})
26  0.518600                      frozenset({SHOES, ABIS_BOOK})
27  0.560175  frozenset({ELECTRONIC_CABLE, CELLULAR_PHONE_CA...
28  0.549234       frozenset({CELLULAR_PHONE_CASE, HEADPHONES})
29  0.533917  frozenset({HEALTH_PERSONAL_CARE, CELLULAR_PHON...
30  0.551422            frozenset({SHIRT, CELLULAR_PHONE_CASE})
31  0.503282    frozenset({ELECTRONIC_CABLE, CHARGING_ADAPTER})
32  0.566740          frozenset({ELECTRONIC_CABLE, HEADPHONES})
33  0.525164  frozenset({ELECTRONIC_CABLE, HEALTH_PERSONAL_C...
34  0.549234               frozenset({SHIRT, ELECTRONIC_CABLE})
35  0.536105      frozenset({HEALTH_PERSONAL_CARE, HEADPHONES})
36  0.536105                     frozenset({SHIRT, HEADPHONES})
37  0.542670           frozenset({SHIRT, HEALTH_PERSONAL_CARE})
38  0.507659                          frozenset({PANTS, SHIRT})
39  0.509847  frozenset({ELECTRONIC_CABLE, CELLULAR_PHONE_CA...
40  0.509847  frozenset({SHIRT, CELLULAR_PHONE_CASE, ABIS_BO...

In [ ]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5, num_itemsets=len(transaction_data.index))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({CELLULAR_PHONE_CASE}),frozenset({ABIS_BOOK}),0.687090,0.831510,0.617068,0.898089,1.080070,1.0,0.045746,1.653310,0.236919,0.684466,0.395153,0.820097
1,frozenset({ABIS_BOOK}),frozenset({CELLULAR_PHONE_CASE}),0.831510,0.687090,0.617068,0.742105,1.080070,1.0,0.045746,1.213326,0.439993,0.684466,0.175819,0.820097
2,frozenset({CHARGING_ADAPTER}),frozenset({ABIS_BOOK}),0.590810,0.831510,0.512035,0.866667,1.042281,1.0,0.020771,1.263676,0.099136,0.562500,0.208658,0.741228
3,frozenset({ABIS_BOOK}),frozenset({CHARGING_ADAPTER}),0.831510,0.590810,0.512035,0.615789,1.042281,1.0,0.020771,1.065016,0.240759,0.562500,0.061047,0.741228
4,frozenset({ELECTRONIC_CABLE}),frozenset({ABIS_BOOK}),0.704595,0.831510,0.614880,0.872671,1.049501,1.0,0.029002,1.323264,0.159668,0.667458,0.244293,0.806072
5,frozenset({ABIS_BOOK}),frozenset({ELECTRONIC_CABLE}),0.831510,0.704595,0.614880,0.739474,1.049501,1.0,0.029002,1.133877,0.279937,0.667458,0.118070,0.806072
6,frozenset({HEADPHONES}),frozenset({ABIS_BOOK}),0.698031,0.831510,0.603939,0.865204,1.040521,1.0,0.023519,1.249962,0.128965,0.652482,0.199976,0.795760
7,frozenset({ABIS_BOOK}),frozenset({HEADPHONES}),0.831510,0.698031,0.603939,0.726316,1.040521,1.0,0.023519,1.103350,0.231131,0.652482,0.093669,0.795760
8,frozenset({HEALTH_PERSONAL_CARE}),frozenset({ABIS_BOOK}),0.676149,0.831510,0.592998,0.877023,1.054735,1.0,0.030773,1.370091,0.160242,0.648325,0.270121,0.795090
9,frozenset({ABIS_BOOK}),frozenset({HEALTH_PERSONAL_CARE}),0.831510,0.676149,0.592998,0.713158,1.054735,1.0,0.030773,1.129023,0.307998,0.648325,0.114278,0.795090
10,frozenset({NUTRITIONAL_SUPPLEMENT}),frozenset({ABIS_BOOK}),0.564551,0.831510,0.509847,0.903101,1.086098,1.0,0.040417,1.738818,0.182048,0.575309,0.424897,0.758129
11,frozenset({ABIS_BOOK}),frozenset({NUTRITIONAL_SUPPLEMENT}),0.831510,0.564551,0.509847,0.613158,1.086098,1.0,0.040417,1.125649,0.470487,0.575309,0.111624,0.758129
12,frozenset({PANTS}),frozenset({ABIS_BOOK}),0.566740,0.831510,0.520788,0.918919,1.105121,1.0,0.049538,2.078045,0.219548,0.593516,0.518779,0.772617
13,frozenset({ABIS_BOOK}),frozenset({PANTS}),0.831510,0.566740,0.520788,0.626316,1.105121,1.0,0.049538,1.159429,0.564553,0.593516,0.137507,0.772617
14,frozenset({SHIRT}),frozenset({ABIS_BOOK}),0.711160,0.831510,0.641138,0.901538,1.084219,1.0,0.049802,1.711228,0.268926,0.711165,0.415624,0.836296
15,frozenset({ABIS_BOOK}),frozenset({SHIRT}),0.831510,0.711160,0.641138,0.771053,1.084219,1.0,0.049802,1.261601,0.461017,0.711165,0.207356,0.836296
16,frozenset({SHOES}),frozenset({ABIS_BOOK}),0.573304,0.831510,0.518600,0.904580,1.087877,1.0,0.041892,1.765777,0.189311,0.585185,0.433677,0.764132
17,frozenset({ABIS_BOOK}),frozenset({SHOES}),0.831510,0.573304,0.518600,0.623684,1.087877,1.0,0.041892,1.133877,0.479424,0.585185,0.118070,0.764132
18,frozenset({ELECTRONIC_CABLE}),frozenset({CELLULAR_PHONE_CASE}),0.704595,0.687090,0.560175,0.795031,1.157099,1.0,0.076055,1.526623,0.459606,0.673684,0.344959,0.805159
19,frozenset({CELLULAR_PHONE_CASE}),frozenset({ELECTRONIC_CABLE}),0.687090,0.704595,0.560175,0.815287,1.157099,1.0,0.076055,1.599261,0.433894,0.673684,0.374711,0.805159
20,frozenset({CELLULAR_PHONE_CASE}),frozenset({HEADPHONES}),0.687090,0.698031,0.549234,0.799363,1.145169,1.0,0.069624,1.505054,0.405121,0.657068,0.335572,0.793098
21,frozenset({HEADPHONES}),frozenset({CELLULAR_PHONE_CASE}),0.698031,0.687090,0.549234,0.786834,1.145169,1.0,0.069624,1.467917,0.419799,0.657068,0.318763,0.793098
22,frozenset({HEALTH_PERSONAL_CARE}),frozenset({CELLULAR_PHONE_CASE}),0.676149,0.687090,0.533917,0.789644,1.149259,1.0,0.069342,1.487527,0.401030,0.643799,0.327743,0.783357
23,frozenset({CELLULAR_PHONE_CASE}),frozenset({HEALTH_PERSONAL_CARE}),0.687090,0.676149,0.533917,0.777070,1.149259,1.0,0.069342,1.452704,0.415052,0.643799,0.311629,0.783357
24,frozenset({SHIRT}),frozenset({CELLULAR_PHONE_CASE}),0.711160,0.687090,0.551422,0.775385,1.128506,1.0,0.062792,1.393094,0.394240,0.651163,0.282173,0.788966
25,frozenset({CELLULAR_PHONE_CASE}),frozenset({SHIRT}),0.687090,0.711160,0.551422,0.802548,1.128506,1.0,0.062792,1.462836,0.363914,0.651163,0.316396,0.788966
26,frozenset({ELECTRONIC_CABLE}),frozenset({CHARGING_ADAPTER}),0.704595,0.590810,0.503282,0.714286,1.208995,1.0,0.087001,1.432166,0.585185,0.635359,0.301757,0.783069
27,frozenset({CHARGING_ADAPTER}),frozenset({ELECTRONIC_CABLE}),0.590810,0.704595,0.503282,0.851852,1.208995,1.0,0.087001,1.993982,0.422460,0.635359,0.498491,0.783069
28,frozenset({ELECTRONIC_CABLE}),frozenset({HEADPHONES}),0.704595,0.698031,0.566740,0.804348,1.152310,1.0,0.074911,1.543399,0.447447,0.678010,0.352079,0.808130
29,frozenset({HEADPHONES}),frozenset({ELECTRONIC_CABLE}),0.698031,0.704595,0.566740,0.811912,1.152310,1.0,0.074911,1.570569,0.437720,0.678010,0.363288,0.808130
30,frozenset({ELECTRONIC_CABLE}),frozenset({HEALTH_PERSONAL_CARE}),0.704595,0.676149,0.525164,0.745342,1.102334,1.0,0.048753,1.271708,0.314259,0.613811,0.213656,0.761020
31,frozenset({HEALTH_PERSONAL_CARE}),frozenset({ELECTRONIC_CABLE}),0.676149,0.704595,0.525164,0.776699,1.102334,1.0,0.048753,1.322900,0.286655,0.613811,0.244085,0.761020
32,frozenset({SHIRT}),frozenset({ELECTRONIC_CABLE}),0.711160,0.704595,0.549234,0.772308,1.096101,1.0,0.048154,1.297386,0.303543,0.633838,0.229219,0.775905
33,frozenset({ELECTRONIC_CABLE}),frozenset({SHIRT}),0.704595,0.711160,0.549234,0.779503,1.096101,1.0,0.048154,1.309952,0.296798,0.633838,0.236613,0.775905
34,frozenset({HEALTH_PERSONAL_CARE}),frozenset({HEADPHONES}),0.676149,0.698031,0.536105,0.792880,1.135882,1.0,0.064132,1.457946,0.369388,0.639687,0.314103,0.780453
35,frozenset({HEADPHONES}),frozenset({HEALTH_PERSONAL_CARE}),0.698031,0.676149,0.536105,0.768025,1.135882,1.0,0.064132,1.396061,0.396155,0.639687,0.283699,0.780453
36,frozenset({SHIRT}),frozenset({HEADPHONES}),0.711160,0.698031,0.536105,0.753846,1.079961,1.0,0.039694,1.226751,0.256339,0.614035,0.184838,0.760936
37,frozenset({HEADPHONES}),frozenset({SHIRT}),0.698031,0.711160,0.536105,0.768025,1.079961,1.0,0.039694,1.245136,0.245194,0.614035,0.196875,0.760936
38,frozenset({SHIRT}),frozenset({HEALTH_PERSONAL_CARE}),0.711160,0.676149,0.542670,0.763077,1.128564,1.0,0.061820,1.366904,0.394398,0.642487,0.268420,0.782833
39,frozenset({HEALTH_PERSONAL_CARE}),frozenset({SHIRT}),0.676149,0.711160,0.542670,0.802589,1.128564,1.0,0.061820,1.463142,0.351760,0.642487,0.316539,0.782833
40,frozenset({PANTS}),frozenset({SHIRT}),0.566740,0.711160,0.507659,0.895753,1.259566,1.0,0.104616,2.770727,0.475640,0.659091,0.639084,0.804800
41,frozenset({SHIRT}),frozenset({PANTS}),0.711160,0.566740,0.507659,0.713846,1.259566,1.0,0.104616,1.514082,0.713460,0.659091,0.339534,0.804800
42,"frozenset({ELECTRONIC_CABLE, CELLULAR_PHONE_CA...",frozenset({ABIS_BOOK}),0.560175,0.831510,0.509847,0.910156,1.094583,1.0,0.044056,1.875369,0.196464,0.578164,0.466772,0.761657
43,"frozenset({ELECTRONIC_CABLE, ABIS_BOOK})",frozenset({CELLULAR_PHONE_CASE}),0.614880,0.687090,0.509847,0.829181,1.206802,1.0,0.087369,1.831829,0.444962,0.643646,0.454098,0.785610
44,"frozenset({CELLULAR_PHONE_CASE, ABIS_BOOK})",frozenset({ELECTRONIC_CABLE}),0.617068,0.704595,0.509847,0.826241,1.172647,1.0,0.075064,1.700085,0.384476,0.628032,0.411794,0.774922
45,frozenset({ELECTRONIC_CABLE}),"frozenset({CELLULAR_PHONE_CASE, ABIS_BOOK})",0.704595,0.617068,0.509847,0.723602,1.172647,1.0,0.075064,1.385440,0.498395,0.628032,0.278208,0.774922
46,frozenset({CELLULAR_PHONE_CASE}),"frozenset({ELECTRONIC_CABLE, ABIS_BOOK})",0.687090,0.614880,0.509847,0.742038,1.206802,1.0,0.087369,1.492936,0.547645,0.643646,0.330179,0.785610
47,frozenset({ABIS_BOOK}),"frozenset({ELECTRONIC_CABLE, CELLULAR_PHONE_CA...",0.831510,0.560175,0.509847,0.613158,1.094583,1.0,0.044056,1.136962,0.512848,0.578164,0.120463,0.761657
48,"frozenset({SHIRT, CELLULAR_PHONE_CASE})",frozenset({ABIS_BOOK}),0.551422,0.831510,0.509847,0.924603,1.111957,1.0,0.051334,2.234712,0.224453,0.583960,0.552515,0.768881
49,"frozenset({SHIRT, ABIS_BOOK})",frozenset({CELLULAR_PHONE_CASE}),0.641138,0.687090,0.509847,0.795222,1.157377,1.0,0.069328,1.528045,0.378912,0.622995,0.345569,0.768630
50,"frozenset({CELLULAR_PHONE_CASE, ABIS_BOOK})",frozenset({SHIRT}),0.617068,0.711160,0.509847,0.826241,1.161822,1.0,0.071013,1.662305,0.363728,0.622995,0.398426,0.771582
51,frozenset({SHIRT}),"frozenset({CELLULAR_PHONE_CASE, ABIS_BOOK})",0.711160,0.617068,0.509847,0.716923,1.161822,1.0,0.071013,1.352750,0.482215,0.622995,0.260765,0.771582
52,frozenset({CELLULAR_PHONE_CASE}),"frozenset({SHIRT, ABIS_BOOK})",0.687090,0.641138,0.509847,0.742038,1.157377,1.0,0.069328,1.391145,0.434557,0.622995,0.281167,0.768630
53,frozenset({ABIS_BOOK}),"frozenset({SHIRT, CELLULAR_PHONE_CASE})",0.831510,0.551422,0.509847,0.613158,1.111957,1.0,0.051334,1.159589,0.597570,0.583960,0.137625,0.768881